name: release please version bump changelog

on:
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  bump-version-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: release please version bump changelog
        uses: grafana/plugin-ci-workflows/actions/plugins/release-please-version-bump-changelog@main # zizmor: ignore[unpinned-uses]
