name: Version bump, changelog

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Semver type of new version (major / minor / patch)"
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
      generate-changelog:
        description: "Generate changelog"
        required: false
        type: boolean
        default: true

permissions:
  contents: read
  id-token: write

jobs:
  bump-version:
    runs-on: ubuntu-x64-small

    steps:
      - name: Version bump
        uses: grafana/plugin-ci-workflows/actions/plugins/version-bump-changelog@ci-cd-workflows/v3.1.0
        with:
          generate-changelog: ${{ inputs.generate-changelog }}
          version: ${{ inputs.version }}
