# Bumps the npm version, creates a git tag and optionally generates a changelog
# entry using conventional commits.
#
# This workflow commits directly to main. It is only suitable for private
# repositories without a branch ruleset that requires a pull request before
# updating main. Public Grafana repositories, and any repo where main is
# protected and requires a PR, cannot use this workflow.
#
# IMPORTANT: This workflow requires the `grafana-plugins-platform-bot` GitHub App
# to have permissions on your repository and GATB (GitHub App Token Broker) setup in deployment_tools.
# Before using it, request permissions by following the instructions here:
#   https://enghub.grafana-ops.net/docs/default/component/grafana-plugins-platform/plugins-ci-github-actions/035-github-app-permissions
# Skipping this step will cause this workflow to fail.

name: Version bump, changelog

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Semver type of new version (major / minor / patch)"
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
      generate-changelog:
        description: "Generate changelog"
        required: false
        type: boolean
        default: true

permissions:
  contents: read
  id-token: write

jobs:
  bump-version:
    runs-on: ubuntu-x64-small

    steps:
      - name: Version bump
        uses: grafana/plugin-ci-workflows/actions/plugins/version-bump-changelog@plugins-version-bump-changelog/v2.0.0
        with:
          generate-changelog: ${{ inputs.generate-changelog }}
          version: ${{ inputs.version }}
