# Description:
# Change plugin scope.
# It uses action grafana/plugin-ci-workflows/actions/plugins/publish/promote-plugin
# to change plugin scope to universal.
# The following inputs should be provided:
# - environment: Target environment (dev, ops, prod)
# - scopes: Scopes to change to. Can be 'universal', 'grafana_cloud', 'grafana_cloud_org' or 'grafana_cloud_instance'.
#           Multiple values can be provided separated by commas.
# - plugin_id: Plugin ID to change scope
# - plugin_version: Plugin version to change scope
#

name: Plugins - Change Plugin Scope

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - ops
          - prod
      plugin_id:
        description: 'Plugin ID to change scope'
        required: false
        type: string
      plugin_version:
        description: 'Plugin version to change scope'
        required: true
        type: string
      scopes:
        description: |
          Scope to change the plugin to.
          Can be 'universal', 'grafana_cloud', 'grafana_cloud_org' or 'grafana_cloud_instance'.
          Multiple values can be provided separated by commas.
        required: false
        type: string

jobs:
  promote:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    env:
      # Set defaults for PR triggers, use inputs for manual dispatch
      ENVIRONMENT: ${{ inputs.environment || 'dev' }}
      PLUGIN_ID: ${{ inputs.plugin_id || 'hugooshiro-dummy-datasource' }}
      PLUGIN_VERSION: ${{ inputs.plugin_version || '1.0.5' }}
      SCOPES: ${{ inputs.scopes || 'universal' }}

    steps:
      - name: Login to Google Cloud (ID token for IAP)
        id: gcloud
        uses: google-github-actions/auth@ba79af03959ebeac9769e648f473a284504d9193 # v2.1.10
        if: ${{ env.ENVIRONMENT != 'prod' }}
        with:
          workload_identity_provider: "projects/304398677251/locations/global/workloadIdentityPools/github/providers/github-provider"
          service_account: github-plugin-ci-workflows@grafanalabs-workload-identity.iam.gserviceaccount.com
          token_format: id_token
          id_token_audience: 194555723165-aftshfqa32nig79trcrh96ha94ta46jd.apps.googleusercontent.com
          id_token_include_email: true
          create_credentials_file: false
          export_environment_variables: false

      - name: Get secrets from Vault
        id: get-secrets
        uses: grafana/shared-workflows/actions/get-vault-secrets@9f37f656e063f0ad0b0bfc38d49894b57d363936 # v1.2.1
        with:
          vault_instance: ${{ env.VAULT_INSTANCE }}
          common_secrets: |
            GCOM_PUBLISH_TOKEN_DEV=plugins/gcom-publish-token:dev
            GCOM_PUBLISH_TOKEN_OPS=plugins/gcom-publish-token:ops
            GCOM_PUBLISH_TOKEN_PROD=plugins/gcom-publish-token:prod
          export_env: false

      - name: Determine which token to use
        run: |
          if [ "${ENVIRONMENT}" == 'dev' ]; then
            echo "Picked dev token"
            token="${{ fromJSON(steps.get-secrets.outputs.secrets).GCOM_PUBLISH_TOKEN_DEV }}"
          elif [ "${ENVIRONMENT}" == 'ops' ]; then
            echo "Picked ops token"
            token="${{ fromJSON(steps.get-secrets.outputs.secrets).GCOM_PUBLISH_TOKEN_OPS }}"
          elif [ "${ENVIRONMENT}" == 'prod' ]; then
            echo "Picked prod token"
            token="${{ fromJSON(steps.get-secrets.outputs.secrets).GCOM_PUBLISH_TOKEN_PROD }}"
          else
            echo "Invalid environment: ${ENVIRONMENT}"
            exit 1
          fi
          echo "GCOM_PUBLISH_TOKEN=$token" >> "$GITHUB_ENV"
        shell: bash
        env:
          ENVIRONMENT: ${{ env.ENVIRONMENT }}

      - name: Change plugin scope
        # this branch will be change once accepted
        uses: grafana/plugin-ci-workflows/actions/plugins/publish/change-plugin-scope@add-promote-plugin-action # zizmor: ignore[unpinned-uses]
        with:
          plugin-id: ${{ env.PLUGIN_ID }}
          plugin-version: ${{ env.PLUGIN_VERSION }}
          environment: ${{ env.ENVIRONMENT }}
          gcom-token: ${{ env.GCOM_PUBLISH_TOKEN }}
          gcloud-auth-token: ${{ steps.gcloud.outputs.id_token }}
          scopes: ${{ env.SCOPE }}
