name: PR Conventional Commit Validation

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-title:
    permissions:
      pull-requests: read
    runs-on: ubuntu-x64-small
    steps:
      - uses: amannn/action-semantic-pull-request@48f256284bd46cdaab1048c3721360e808335d50 # v6.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
