name: PR Conventional Commit Validation

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-title:
    permissions:
      pull-requests: read
    runs-on: ubuntu-x64-small
    steps:
      - uses: amannn/action-semantic-pull-request@48f256284bd46cdaab1048c3721360e808335d50 # v6.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  check-references:
    runs-on: ubuntu-arm64-small
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Switch references
        id: switch-references
        uses: grafana/plugin-ci-workflows/actions/internal/switch-references@main
        with:
          repository: grafana/plugin-ci-workflows
          ref: main
          paths: |
            .github/workflows/ci.yml
            .github/workflows/cd.yml
            .github/workflows/playwright.yml
            .github/workflows/playwright-docker.yml
            actions/plugins/**

      - name: Check drift
        if: steps.switch-references.outputs.changed == 'true'
        run: |
          git diff
          echo "❌ Some references of the 'plugin-ci-workflows' actions are not pointing to the 'main' branch."
          echo "See the diff above for details."
          echo "If this is a leftover from testing, please remove it before merging the PR."

          git diff --unified=0 | awk '
          /^diff --git/ { 
              # Extract filename from "diff --git a/file b/file"
              gsub(/^diff --git a\//, "")
              gsub(/ b\/.*$/, "")
              file = $0
          }
          /^@@/ {
              # Extract line number from "@@ -old +new @@" format
              match($0, /\+([0-9]+)/, arr)
              if (arr[1]) {
                  line = arr[1]
                  print "::error file=" file ",line=" line ",title=TEST::Reference to non-main branch. Please switch it back to `@main`."
              }
          }'

          exit 1
        shell: bash
