# Creates an automated PR to restore the rolling release channel by switching
# all tagged references in workflows and configuration files to point to the
# `main` branch instead of a specific version tag. This is complementary to the
# `release-please PR: Update tagged references` workflow, which updates the
# references to point to specific version tags when a new release is created.
name: "release-please: Restore rolling release"

on:
  push:
    tags:
      # Trigger tags matching the most specific tags created by release-please.
      # When publishing a new release, release-please creates multiple tags like these:
      # - `component/v1.2.3`
      # - `component/v1.2`
      # - `component/v1`
      # We trigger only for the most specific one, otherwise we trigger this workflow multiple times.
      # (we only need one PR for each release, even if multiple tags are updated for the same release)
      - "*/v[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: read

# Only one instance of this workflow should run at a time.
concurrency:
  group: ${{ github.workflow_ref }}
  cancel-in-progress: true

jobs:
  update-tagged-references:
    name: Update tagged references
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    runs-on: ubuntu-arm64-small
    steps:
      - name: Generate GitHub token
        id: generate-github-token
        uses: grafana/shared-workflows/actions/create-github-app-token@259ba21cb3ff07724f331e26d926d655d24b317b # create-github-app-token/v0.2.3
        with:
          github_app: plugins-platform-bot-app

      - name: Checkout main branch
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: main
          token: ${{ steps.generate-github-token.outputs.token }}
          # fetch-depth: 0
          persist-credentials: false

      # Update everything except for the "examples" folder
      # (we want to encourage using tagged releases in docs)
      - name: Switch references
        id: switch-references
        uses: grafana/plugin-ci-workflows/actions/internal/switch-references@main
        with:
          repository: grafana/plugin-ci-workflows
          ref: main
          paths: |
            .github/workflows/ci.yml
            .github/workflows/cd.yml
            .github/workflows/playwright.yml
            .github/workflows/playwright-docker.yml
            .github/workflows/check-release-channel.yml
            actions/plugins/**

      - name: Get bot user info
        id: get-bot-user
        if: steps.switch-references.outputs.changed == 'true'
        uses: grafana/plugin-ci-workflows/actions/internal/get-bot-user@main
        with:
          app-slug: grafana-plugins-platform-bot
          token: ${{ steps.generate-github-token.outputs.token }}

      - name: Create PR
        if: steps.switch-references.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          commit-message: "chore: update references to use 'main' branch"
          title: "chore: update references to use 'main' branch"
          branch: restore-rolling-release/${{ github.ref_name }}
          base: main
          body: |
            This PR updates tagged references in workflow and configuration files to point to the `main` branch
            in order to restore the rolling release channel.

            _This is an automated PR created by the `${{ github.workflow }}` workflow._

            <!--
            BEGIN_COMMIT_OVERRIDE
            no changelog
            END_COMMIT_OVERRIDE
            -->
          committer: ${{ steps.get-bot-user.outputs.committer }}
          token: ${{ steps.generate-github-token.outputs.token }}
