name: Switch GHA references to rolling release

on:
  push:
    tags:
      - "*"

permissions:
  contents: read
  pull-requests: write

jobs:
  switch-references:
    name: Switch references
    runs-on: ubuntu-x64-small
    steps:
      - name: Checkout main branch
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          ref: main
          persist-credentials: false

      - name: Switch references to @main
        uses: grafana/plugin-ci-workflows/actions/internal/switch-references@main # zizmor: ignore[unpinned-uses]
        with:
          ref: main
