name: Matrix Output Test

on:
  push:
    branches:
      - academo/use-release-gcs-for-catalogue

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Generate random strings array
        id: set-matrix
        run: |
          # Generate 1-5 random strings
          count=$((RANDOM % 5 + 1))
          strings=()
          
          for ((i=1; i<=count; i++)); do
            # Generate random string using openssl
            random_string=$(openssl rand -hex 4)
            strings+=("\"str-$random_string\"")
          done
          
          # Join array elements with commas
          matrix_json="[$(IFS=,; echo "${strings[*]}")]"
          echo "Generated matrix: $matrix_json"
          echo "matrix=$matrix_json" >> $GITHUB_OUTPUT

  matrix-job:
    runs-on: ubuntu-latest
    needs: generate-matrix
    strategy:
      matrix:
        value: ${{ fromJSON(needs.generate-matrix.outputs.matrix) }}
    outputs:
      # Matrix jobs with same output name will overwrite each other
      result: ${{ steps.process.outputs.result }}
    steps:
      - name: Process matrix value
        id: process
        run: |
          echo "Processing value: ${{ matrix.value }}"
          result="processed-${{ matrix.value }}-$(date +%s)"
          echo "result=$result" >> $GITHUB_OUTPUT
          echo "Generated result: $result"

  collect-results:
    runs-on: ubuntu-latest
    needs: 
      - generate-matrix
      - matrix-job
    steps:
      - name: Display matrix job output
        run: |
          echo "Output from matrix job:"
          echo "result: ${{ needs.matrix-job.outputs.result }}"
          
          echo ""
          echo "All outputs object:"
          echo '${{ toJSON(needs.matrix-job.outputs) }}'
          
          echo ""
          echo "This will show only the result from the last matrix job that completed"
