name: Matrix Output Test

on:
  push:
    branches:
      - academo/use-release-gcs-for-catalogue

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Generate random strings array
        id: set-matrix
        run: |
          # Generate 1-5 random strings
          count=$((RANDOM % 5 + 1))
          strings=()
          
          for ((i=1; i<=count; i++)); do
            # Generate random string using openssl
            random_string=$(openssl rand -hex 4)
            strings+=("\"str-$random_string\"")
          done
          
          # Join array elements with commas
          matrix_json="[$(IFS=,; echo "${strings[*]}")]"
          echo "Generated matrix: $matrix_json"
          echo "matrix=$matrix_json" >> $GITHUB_OUTPUT

  matrix-job:
    runs-on: ubuntu-latest
    needs: generate-matrix
    strategy:
      matrix:
        value: ${{ fromJSON(needs.generate-matrix.outputs.matrix) }}
    steps:
      - name: Process matrix value
        id: process
        run: |
          echo "Processing value: ${{ matrix.value }}"
          result="processed-${{ matrix.value }}-$(date +%s)"
          echo "Generated result: $result"
          echo "{\"${{ matrix.value }}\": \"$result\"}" > result.json

      - name: Upload result to artifact
        uses: actions/upload-artifact@v4
        with:
          name: result-${{ matrix.value }}
          path: result.json
          retention-days: 1

  collect-results:
    runs-on: ubuntu-latest
    needs: 
      - generate-matrix
      - matrix-job
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: result-*
          merge-multiple: true
      - name: Process results
        run: |
          echo "Processing results..."
          for artifact in result-*.json; do
            echo "Processing artifact: $artifact"
            cat "$artifact"
          done
