# Bump npm version, create a git tag and optionally generate a changelog on main.
name: Bump Version and release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Semver type of new version (major / minor / patch)"
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
      generate-changelog:
        description: "Generate changelog"
        required: false
        type: boolean
        default: true
    
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
      - name: Version bump
        uses: grafana/plugin-ci-workflows/actions/plugins/version-bump@l2d2/ci-create-tag # zizmor: ignore[unpinned-uses]      
        with:
          generate-changelog: ${{ inputs.generate-changelog }}
          version: ${{ inputs.version }}